apiVersion: apps/v1
kind: Deployment
metadata:
  name: tax-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tax-service
  template:
    metadata:
      labels:
        app: tax-service
    spec:
      containers:
        - name: tax-service
          image: niranjana1992/tax-service-image:1.0
          ports:
            - containerPort: 4000

