apiVersion: v1
kind: Service
metadata:
  name: spboot-hello-world-docker-service
spec:
  selector:
    app: spboot-hello-world-docker
  type: NodePort
  ports:
    - port: 80
      targetPort: 2828
      nodePort: 32000
