apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-hello-react-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-hello
  template:
    metadata:
      labels:
        app: auth-hello
    spec:
      containers:
        - name: auth-hello-frontend
          image: niranjana1992/auth-app-react-k8s:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: auth-hello-react-service
spec:
  selector:
    app: auth-hello
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
